<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><?php echo $this->settings('name') ?></a>
    </div>
    <div class="collapse navbar-collapse">
        <?php echo $this->navigation('navigation')
                ->menu()
                ->setPartial('partial/menu.phtml')
                ->setUlClass('nav navbar-nav navbar-nav-left')
                ->render();
         ?>
         <ul class="nav navbar-nav navbar-right">
             <li>
                 <?php echo $this->languagesonsite() ?>
             </li>
         <?php if($this->zfcUserIdentity()): ?>
             <li class="dropdown">
                 <a href="/user"><?php echo $this->translate('Preferences') ?></a>
             </li>
             <li class="dropdown">
                 <a href="/user/logout"><?php echo $this->translate('Sign Out') ?></a>
             </li>
         <?php else: ?>
                <li class="dropdown">
                    <a href="/user"><?php echo $this->translate('Log In') ?></a>
                </li>
         <?php endif; ?>
             <li>
                 <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" title="<?php echo $this->translate('Type here who you are looking for or what you are looking for')?>" size="" class="form-control input-md" placeholder="<?php echo $this->translate('Search ...')?>" id="searchbox">
                    </div>
                 </form>
             </li>
         </ul>
    </div>
</nav>

