<?php echo $this->doctype(); ?>

<html lang="<?php echo \Locale::getPrimaryLanguage(Locale::getDefault())?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->partial('partial/head.phtml'); ?>
    </head>
    <body data-spy="scroll" data-target=".scrollspy" >
        <?php echo !$this->settings('active') ? "<div class='alert alert-warning'>" . $this->translate('This website is on maintenance mode') . "</div>" : null?>
        <?php echo $this->partial('partial/header.phtml'); ?>
        <div class="wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->flashMessage(); ?>
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->partial('partial/footer'); ?>
        <?php echo $this->inlineScript(); ?>
        <?php echo $this->settings('bodyscript')?>
    </body>
</html>
